export enum ActionTypes {
    MOVE_CELL = 'MOVE_CELL',
    UPDATE_CELL = 'UPDATE_CELL',
    DELETE_CELL = 'DELETE_CELL',
    INSERT_CELL_AFTER = 'INSERT_CELL_AFTER',
    BUNDLE_START = 'BUNDLE_START',
    BUNDLE_END = 'BUNDLE_END',
    FETCH_CELLS_START = 'FETCH_CELLS_START',
    FETCH_CELLS_END = 'FETCH_CELLS_END',
    FETCH_CELLS_ERROR = 'FETCH_CELLS_ERROR'
};